CREATE OR REPLACE VIEW voice_identification_panda
AS
SELECT 1                                    AS record_id,
       ident.identification_receipt_number  AS primary_key1,
       CAST( '0' AS VARCHAR2( 256 ) )       AS primary_key2,
       CAST( '0' AS VARCHAR2( 256 ) )       AS primary_key3,
       CAST( '0' AS VARCHAR2( 256 ) )       AS primary_key4,
       to_char( ident.voice_engagement_number ) AS foreign_key1,
       ident.lte_three_g_engagement_number  AS foreign_key2,
       ident.user_id                        AS foreign_key3,
       null                                 AS foreign_key4,
       null                                 AS foreign_key5,
       null                                 AS foreign_key6,
       null                                 AS foreign_key7,
       null                                 AS foreign_key8,
       null                                 AS foreign_key9,
       null                                 AS foreign_key10,
       null                                 AS foreign_key11,
       null                                 AS foreign_key12,
       null                                 AS foreign_key13,
       null                                 AS foreign_key14,
       null                                 AS foreign_key15,
       null                                 AS foreign_key16,
       null                                 AS foreign_key17,
       null                                 AS foreign_key18,
       null                                 AS foreign_key19,
       null                                 AS foreign_key20,
       null                                 AS namespaces1,
       null                                 AS namespaces2,
       null                                 AS namespaces3,
       null                                 AS index_free1,
       null                                 AS index_free2,
       null                                 AS index_free3,
       null                                 AS index_free4,
       null                                 AS index_free5,
       null                                 AS index_free6,
       null                                 AS index_free7,
       null                                 AS index_free8,
       null                                 AS index_free9,
       null                                 AS index_free10,
       CAST( null AS DATE )                 AS index_free_date1,
       CAST( null AS DATE )                 AS index_free_date2,
       CAST( null AS DATE )                 AS index_free_date3,
       CAST( null AS DATE )                 AS index_free_date4,
       CAST( null AS DATE )                 AS index_free_date5,
       CAST( null AS DATE )                 AS index_free_date6,
       CAST( null AS DATE )                 AS index_free_date7,
       CAST( null AS DATE )                 AS index_free_date8,
       CAST( null AS DATE )                 AS index_free_date9,
       CAST( null AS DATE )                 AS index_free_date10,
       to_char( id_up.upload_count )        AS item_free1,
       to_char( id_up.first_upload_date_time, 'YYYYMMDDHH24MISS' ) AS item_free2,
       id_up.identification_receipt_number  AS item_free3,
       ident.voice_clerk_request_status     AS item_free4,
       id_re.identification_doc_type        AS item_free5,
       id_re.identification_sub_doc_type    AS item_free6,
       id_re.document_acceptance_means      AS item_free7,
       ident.identification_status          AS item_free8,
       id_ng.ng_reason                      AS item_free9,
       id_ng.ng_reason_detail               AS item_free10,
       id_re.execution_date                 AS item_free11,
       id_re.operator_id                    AS item_free12,
       null                                 AS item_free13,
       null                                 AS item_free14,
       null                                 AS item_free15,
       null                                 AS item_free16,
       null                                 AS item_free17,
       null                                 AS item_free18,
       null                                 AS item_free19,
       null                                 AS item_free20,
       null                                 AS item_free21,
       null                                 AS item_free22,
       null                                 AS item_free23,
       null                                 AS item_free24,
       null                                 AS item_free25,
       null                                 AS item_free26,
       null                                 AS item_free27,
       null                                 AS item_free28,
       null                                 AS item_free29,
       null                                 AS item_free30,
       null                                 AS item_free31,
       null                                 AS item_free32,
       null                                 AS item_free33,
       null                                 AS item_free34,
       null                                 AS item_free35,
       null                                 AS item_free36,
       null                                 AS item_free37,
       null                                 AS item_free38,
       null                                 AS item_free39,
       null                                 AS item_free40,
       null                                 AS item_free41,
       null                                 AS item_free42,
       null                                 AS item_free43,
       null                                 AS item_free44,
       null                                 AS item_free45,
       null                                 AS item_free46,
       null                                 AS item_free47,
       null                                 AS item_free48,
       null                                 AS item_free49,
       null                                 AS item_free50,
       null                                 AS item_free51,
       null                                 AS item_free52,
       null                                 AS item_free53,
       null                                 AS item_free54,
       null                                 AS item_free55,
       null                                 AS item_free56,
       null                                 AS item_free57,
       null                                 AS item_free58,
       null                                 AS item_free59,
       null                                 AS item_free60,
       null                                 AS item_free61,
       null                                 AS item_free62,
       null                                 AS item_free63,
       null                                 AS item_free64,
       null                                 AS item_free65,
       null                                 AS item_free66,
       null                                 AS item_free67,
       null                                 AS item_free68,
       null                                 AS item_free69,
       null                                 AS item_free70,
       null                                 AS item_free71,
       null                                 AS item_free72,
       null                                 AS item_free73,
       null                                 AS item_free74,
       null                                 AS item_free75,
       null                                 AS item_free76,
       null                                 AS item_free77,
       null                                 AS item_free78,
       null                                 AS item_free79,
       null                                 AS item_free80,
       null                                 AS item_free81,
       null                                 AS item_free82,
       null                                 AS item_free83,
       null                                 AS item_free84,
       null                                 AS item_free85,
       null                                 AS item_free86,
       null                                 AS item_free87,
       null                                 AS item_free88,
       null                                 AS item_free89,
       null                                 AS item_free90,
       null                                 AS item_free91,
       null                                 AS item_free92,
       null                                 AS item_free93,
       null                                 AS item_free94,
       null                                 AS item_free95,
       null                                 AS item_free96,
       null                                 AS item_free97,
       null                                 AS item_free98,
       null                                 AS item_free99,
       null                                 AS item_free100,
       null                                 AS item_free101,
       null                                 AS item_free102,
       null                                 AS item_free103,
       null                                 AS item_free104,
       null                                 AS item_free105,
       null                                 AS item_free106,
       null                                 AS item_free107,
       null                                 AS item_free108,
       null                                 AS item_free109,
       null                                 AS item_free110,
       null                                 AS item_free111,
       null                                 AS item_free112,
       null                                 AS item_free113,
       null                                 AS item_free114,
       null                                 AS item_free115,
       null                                 AS item_free116,
       null                                 AS item_free117,
       null                                 AS item_free118,
       null                                 AS item_free119,
       null                                 AS item_free120,
       null                                 AS item_free121,
       null                                 AS item_free122,
       null                                 AS item_free123,
       null                                 AS item_free124,
       null                                 AS item_free125,
       null                                 AS item_free126,
       null                                 AS item_free127,
       null                                 AS item_free128,
       null                                 AS item_free129,
       null                                 AS item_free130,
       null                                 AS item_free131,
       null                                 AS item_free132,
       null                                 AS item_free133,
       null                                 AS item_free134,
       null                                 AS item_free135,
       null                                 AS item_free136,
       null                                 AS item_free137,
       null                                 AS item_free138,
       null                                 AS item_free139,
       null                                 AS item_free140,
       null                                 AS item_free141,
       null                                 AS item_free142,
       null                                 AS item_free143,
       null                                 AS item_free144,
       null                                 AS item_free145,
       null                                 AS item_free146,
       null                                 AS item_free147,
       null                                 AS item_free148,
       null                                 AS item_free149,
       null                                 AS item_free150,
       null                                 AS item_free151,
       null                                 AS item_free152,
       null                                 AS item_free153,
       null                                 AS item_free154,
       null                                 AS item_free155,
       null                                 AS item_free156,
       null                                 AS item_free157,
       null                                 AS item_free158,
       null                                 AS item_free159,
       null                                 AS item_free160,
       null                                 AS item_free161,
       null                                 AS item_free162,
       null                                 AS item_free163,
       null                                 AS item_free164,
       null                                 AS item_free165,
       null                                 AS item_free166,
       null                                 AS item_free167,
       null                                 AS item_free168,
       null                                 AS item_free169,
       null                                 AS item_free170,
       null                                 AS item_free171,
       null                                 AS item_free172,
       null                                 AS item_free173,
       null                                 AS item_free174,
       null                                 AS item_free175,
       null                                 AS item_free176,
       null                                 AS item_free177,
       null                                 AS item_free178,
       null                                 AS item_free179,
       null                                 AS item_free180,
       null                                 AS item_free181,
       null                                 AS item_free182,
       null                                 AS item_free183,
       null                                 AS item_free184,
       null                                 AS item_free185,
       null                                 AS item_free186,
       null                                 AS item_free187,
       null                                 AS item_free188,
       null                                 AS item_free189,
       null                                 AS item_free190,
       null                                 AS item_free191,
       null                                 AS item_free192,
       null                                 AS item_free193,
       null                                 AS item_free194,
       null                                 AS item_free195,
       null                                 AS item_free196,
       null                                 AS item_free197,
       null                                 AS item_free198,
       null                                 AS item_free199,
       null                                 AS item_free200,
       CAST( null AS DATE )                 AS item_free_date1,
       CAST( null AS DATE )                 AS item_free_date2,
       CAST( null AS DATE )                 AS item_free_date3,
       CAST( null AS DATE )                 AS item_free_date4,
       CAST( null AS DATE )                 AS item_free_date5,
       CAST( null AS DATE )                 AS item_free_date6,
       CAST( null AS DATE )                 AS item_free_date7,
       CAST( null AS DATE )                 AS item_free_date8,
       CAST( null AS DATE )                 AS item_free_date9,
       CAST( null AS DATE )                 AS item_free_date10,
       null                                 AS create_id,
       CAST( null AS DATE )                 AS create_date,
       null                                 AS update_id,
       sysdate                              AS update_date,
       CAST( null AS DATE )                 AS delete_date
FROM voice_identification_state ident
  LEFT OUTER JOIN voice_identification_upload_s id_up ON ident.identification_receipt_number = id_up.identification_receipt_number
  LEFT OUTER JOIN voice_identification_result_s id_re ON ident.identification_receipt_number = id_re.identification_receipt_number
  LEFT OUTER JOIN voice_identification_ng_s     id_ng ON id_re.identification_result_id      = id_ng.identification_result_id
WHERE
  ident.identification_receipt_number IN (
    SELECT identification_receipt_number FROM voice_identification_event    WHERE event_date >= trunc(sysdate-1,'DD')
    UNION
    SELECT identification_receipt_number FROM voice_identification_upload_e WHERE event_date >= trunc(sysdate-1,'DD')
    UNION
    SELECT identification_receipt_number FROM voice_identification_result_e WHERE event_date >= trunc(sysdate-1,'DD')
      OR identification_result_id IN (
         SELECT identification_result_id FROM voice_identification_ng_e     WHERE event_date >= trunc(sysdate-1,'DD')
      )
  );
